 - hosts: remoto
   tasks:
   - name: Instalando mongodb
     apt:
       name: mongodb
       update_cache: yes
       state: present
       
     notify:
       - enable mongodb
   - name: Enable and start mongodb
     systemd:
       state: started
       name: mongodb
       enabled: yes
   
   - name: Python Requiments
     apt:
      name: python3
      update_cache: yes
      state: present
   